(function () {
  "use strict";
  const stage=document.getElementById("discoverStage"),cardWrap=document.getElementById("cardWrap"),progress=document.getElementById("cardProgress"),savedProgress=document.getElementById("savedProgress"),progressBar=document.getElementById("progressBar"),toast=document.getElementById("swipeToast"),actions=document.getElementById("discoverActions"),skipBtn=document.getElementById("skipBtn"),saveBtn=document.getElementById("saveBtn"),clinicBtn=document.getElementById("clinicBtn"),savedNavCount=document.getElementById("savedNavCount"),emailModal=document.getElementById("emailModal"),emailForm=document.getElementById("emailForm"),emailSuccess=document.getElementById("emailSuccess");
  if(!stage||!cardWrap||typeof TREATMENTS==="undefined")return;
  const FAV_KEY="wf_favourites",EMAIL_KEY="wf_discover_email",PROMPT_KEY="wf_email_prompt_seen";
  const images=[
    "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1000&q=82",
    "https://images.unsplash.com/photo-1559757175-7b21e7afae08?auto=format&fit=crop&w=1000&q=82"
  ];
  let index=0,locked=false,activePointer=null,startX=0,startY=0,deltaX=0,deltaY=0,currentCard=null;
  function getSaved(){try{return JSON.parse(localStorage.getItem(FAV_KEY))||[]}catch(_){return[]}}
  function saveTreatment(name){const saved=getSaved();if(!saved.includes(name)){saved.push(name);try{localStorage.setItem(FAV_KEY,JSON.stringify(saved))}catch(_){}}return saved.length}
  function escapeHTML(value){return String(value).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
  function coverageLabel(t){return t.categories&&t.categories.length?t.categories.join(" or "):t.billed}
  function clinicLink(t){return t.link||"/#directory"}
  function updateMeta(){const saved=getSaved();progress.textContent=Math.min(index+1,TREATMENTS.length)+" of "+TREATMENTS.length;savedProgress.textContent=saved.length+" saved";savedNavCount.textContent=saved.length;progressBar.style.width=Math.min(index/TREATMENTS.length*100,100)+"%";if(index<TREATMENTS.length)clinicBtn.href=clinicLink(TREATMENTS[index])}
  function maybePromptEmail(){if(!emailModal||localStorage.getItem(EMAIL_KEY)||sessionStorage.getItem(PROMPT_KEY))return;sessionStorage.setItem(PROMPT_KEY,"1");window.setTimeout(function(){emailModal.showModal()},750)}
  function renderCard(){
    updateMeta();
    if(index>=TREATMENTS.length){progress.textContent="Complete";progressBar.style.width="100%";actions.hidden=true;const count=getSaved().length;cardWrap.innerHTML='<section class="discover-complete"><div><div class="complete-mark" aria-hidden="true">✓</div><h2>Your wellness shortlist is ready.</h2><p>You saved <strong>'+count+'</strong> benefit'+(count===1?"":"s")+'. View them together, find matching clinics, or send the list to yourself.</p><div class="complete-actions"><a class="btn btn--primary" href="/saved">View saved benefits</a><button class="btn btn--honey" id="emailComplete" type="button">Email my list</button><button class="btn btn--ghost" id="restartDiscover" type="button">Start over</button></div></div></section>';document.getElementById("restartDiscover").addEventListener("click",function(){index=0;actions.hidden=false;renderCard()});document.getElementById("emailComplete").addEventListener("click",function(){emailModal.showModal()});currentCard=null;return}
    const t=TREATMENTS[index],link=clinicLink(t);
    cardWrap.innerHTML='<article class="discover-card entering" tabindex="0" aria-label="'+escapeHTML(t.name)+'. Swipe right to save or left to skip."><span class="choice-stamp choice-stamp--save">Save ♥</span><span class="choice-stamp choice-stamp--skip">Skip</span><div class="card-photo"><img src="'+images[index%images.length]+'" alt="'+escapeHTML(t.name)+'" loading="'+(index===0?"eager":"lazy")+'"><span class="card-kicker">'+escapeHTML(t.group)+'</span></div><div class="card-content"><h2>'+escapeHTML(t.name)+'</h2><p class="card-description">'+escapeHTML(t.desc)+'</p><div class="benefit-check"><div><small>May be covered</small><strong>'+escapeHTML(coverageLabel(t))+'</strong></div><a href="/#insurance">Check this benefit</a></div><div class="card-bottom"><span class="billing-note">Commonly billed under: '+escapeHTML(t.billed)+'</span><a class="inline-clinic" href="'+escapeHTML(link)+'">Find clinics →</a></div></div></article>';
    currentCard=cardWrap.querySelector(".discover-card");currentCard.addEventListener("pointerdown",onPointerDown);currentCard.addEventListener("pointermove",onPointerMove);currentCard.addEventListener("pointerup",onPointerUp);currentCard.addEventListener("pointercancel",onPointerCancel);currentCard.addEventListener("keydown",function(e){if(e.key==="ArrowRight")dismiss("right");if(e.key==="ArrowLeft")dismiss("left")});locked=false
  }
  function onPointerDown(e){if(locked||e.target.closest("a"))return;activePointer=e.pointerId;startX=e.clientX;startY=e.clientY;deltaX=0;deltaY=0;currentCard.classList.remove("entering");currentCard.classList.add("dragging");currentCard.setPointerCapture(e.pointerId)}
  function onPointerMove(e){if(e.pointerId!==activePointer||locked)return;deltaX=e.clientX-startX;deltaY=e.clientY-startY;const r=Math.max(-12,Math.min(12,deltaX/18));currentCard.style.transform="translate3d("+deltaX+"px,"+(deltaY*.16)+"px,0) rotate("+r+"deg)";const s=Math.min(Math.abs(deltaX)/110,1);currentCard.querySelector(".choice-stamp--save").style.opacity=deltaX>0?s:0;currentCard.querySelector(".choice-stamp--skip").style.opacity=deltaX<0?s:0}
  function onPointerUp(e){if(e.pointerId!==activePointer||locked)return;activePointer=null;currentCard.classList.remove("dragging");const threshold=Math.max(80,currentCard.offsetWidth*.2);Math.abs(deltaX)>=threshold?dismiss(deltaX>0?"right":"left"):returnToCenter()}
  function onPointerCancel(){if(locked)return;activePointer=null;if(currentCard){currentCard.classList.remove("dragging");returnToCenter()}}
  function returnToCenter(){if(!currentCard)return;currentCard.style.transition="transform .32s cubic-bezier(.22,.8,.3,1)";currentCard.style.transform="translate3d(0,0,0) rotate(0deg)";currentCard.querySelectorAll(".choice-stamp").forEach(function(el){el.style.opacity=0});window.setTimeout(function(){if(currentCard)currentCard.style.transition=""},340)}
  function showToast(direction,name){toast.className="swipe-toast "+(direction==="right"?"save":"skip");toast.textContent=direction==="right"?"♥ "+name+" saved — view it anytime in Saved":"Skipped — you can still find it in Browse";void toast.offsetWidth;toast.classList.add("show")}
  function dismiss(direction){if(locked||!currentCard)return;locked=true;const t=TREATMENTS[index];let savedCount=getSaved().length;if(direction==="right")savedCount=saveTreatment(t.name);showToast(direction,t.name);updateMeta();const distance=window.innerWidth+currentCard.offsetWidth+180,sign=direction==="right"?1:-1;currentCard.classList.remove("dragging","entering");currentCard.style.transition="transform .56s cubic-bezier(.2,.72,.18,1), opacity .45s ease";currentCard.style.transform="translate3d("+(sign*distance)+"px,-24px,0) rotate("+(sign*18)+"deg)";currentCard.style.opacity="0";window.setTimeout(function(){index+=1;renderCard();if(direction==="right"&&savedCount===2)maybePromptEmail()},580)}
  skipBtn.addEventListener("click",function(){dismiss("left")});saveBtn.addEventListener("click",function(){dismiss("right")});
  document.getElementById("closeEmailModal").addEventListener("click",function(){emailModal.close()});emailModal.addEventListener("click",function(e){if(e.target===emailModal)emailModal.close()});
  emailForm.addEventListener("submit",function(e){e.preventDefault();const input=document.getElementById("discoverEmail");if(!input.checkValidity()){input.reportValidity();return}localStorage.setItem(EMAIL_KEY,input.value.trim());emailForm.hidden=true;emailSuccess.hidden=false});
  renderCard();
})();